// Generated by CoffeeScript 1.3.1
(function() {

  $(window).load(function() {
    var dlog, img, _DEBUG_;
    console.log('HI');
    _DEBUG_ = true;
    dlog = function(msg) {
      if (_DEBUG_) {
        return console.log(msg);
      }
    };
    img = $('#testimage')[0];
    $(img).on('canvasready', function(e, c) {
      return Canio.resize(c, 400, 300, 200, 100, function(c) {
        c.id = 'resizedcanvas';
        return $('#resize_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.scale(c, 0.1, function(c) {
        c.id = 'scaledcanvas';
        return $('#scale_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.crop(c, 580, 330, 100, 100, function(c) {
        c.id = 'cropedcanvas';
        return $('#crop_placeholder').html(c);
      });
    });
    return Canio.byImage(img, function(c) {
      $('#byImage_placeholder').html(c);
      c.id = 'canvasbyimage';
      return $(img).trigger('canvasready', c);
    });
  });

}).call(this);
