// Generated by CoffeeScript 1.3.1
(function() {

  $(window).load(function() {
    var dlog, img, _DEBUG_;
    console.log('HI');
    _DEBUG_ = true;
    dlog = function(msg) {
      if (_DEBUG_) {
        return console.log(msg);
      }
    };
    img = $('#testimage')[0];
    Canio.byImage(img, function(c) {
      return $('#byImage_placeholder').html(c);
    });
    return Canio.byImage(img, function(c) {
      dlog(c);
      return Canio.resize(c, 500, 400, function(c) {
        console.log('hallo');
        dlog(c);
        return $('#resize_placeholder').html(c);
      });
    });
  });

}).call(this);
