// Generated by CoffeeScript 1.3.1
(function() {

  $(window).load(function() {
    var dlog, img, _DEBUG_;
    console.log('HI');
    _DEBUG_ = true;
    dlog = function(msg) {
      if (_DEBUG_) {
        return console.log(msg);
      }
    };
    img = $('#testimage')[0];
    $(img).on('canvasready', function(e, c) {
      return Canio.resize(c, 400, 300, 200, 100, function(c) {
        c.id = 'resizedcanvas';
        return $('#resize_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.scale(c, 0.1, function(c) {
        c.id = 'scaledcanvas';
        return $('#scale_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.crop(c, 580, 330, 100, 100, function(c) {
        c.id = 'cropedcanvas';
        return $('#crop_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.invert(c, function(c) {
        return $('#invert_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.mosaic(c, 8, function(c) {
        return $('#mosaic_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.binarize(c, 0.5, function(c) {
        return $('#binarize_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.noise(c, 90, function(c) {
        return $('#noise_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.vignette(c, 0.2, 0.8, function(c) {
        return $('#vignette_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.saturate(c, 0.2, function(c) {
        return $('#saturate_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.desaturate(c, 0.4, function(c) {
        return $('#desaturate_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.curve(c, function(c) {
        return $('#curve_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Canio.screen(c, 227, 12, 169, 0.9, function(c) {
        return $('#screen_placeholder').html(c);
      });
    });
    return Canio.byImage(img, function(c) {
      $('#byImage_placeholder').html(c);
      c.id = 'canvasbyimage';
      return $(img).trigger('canvasready', c);
    });
  });

}).call(this);
