// Generated by CoffeeScript 1.3.1
(function() {
  var Canio, byArray, byImage, cbr, clamp, copy, crop, dlog, fff, getGrayscaleValue, getToolbox, hardResize, ifw, isFunction, mF, make, nb, newToolbox, resize, rgba, scale, toArray, toImage, _DEBUG_,
    __slice = [].slice;

  Canio = {};

  Canio._DEBUG_ = _DEBUG_ = false;

  dlog = function(msg) {
    if (_DEBUG_) {
      return console.log(msg);
    }
  };

  cbr = function(cb, function_name) {
    var _results;
    _results = [];
    while (!cb) {
      throw new Error('Callback required for ' + function_name);
    }
    return _results;
  };

  isFunction = function(functionToCheck) {
    var getType;
    getType = {};
    return functionToCheck && getType.toString.call(functionToCheck) === '[object Function]';
  };

  nb = function() {
    var cb, p;
    cb = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (cb && isFunction(cb)) {
      window.setTimeout.apply(window, [cb, 0].concat(__slice.call(p)));
    }
    return p != null ? p[0] : void 0;
  };

  fff = function() {
    var defaults, first_func, i, p2, params;
    params = arguments[0], defaults = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    first_func = null;
    p2 = [];
    i = 0;
    while (i < params.length || i < defaults.length) {
      if (typeof params[i] === 'function' && !first_func) {
        first_func = params[i];
      } else {
        if (params[i] !== null && params[i] !== void 0) {
          p2.push(params[i]);
        } else {
          p2.push(defaults[i]);
        }
      }
      i = i + 1;
    }
    if (!first_func) {
      first_func = function(c) {
        return null;
      };
    }
    p2.unshift(first_func);
    dlog(p2);
    return p2;
  };

  clamp = function(v, min, max) {
    if (min == null) {
      min = 0;
    }
    if (max == null) {
      max = 255;
    }
    return Math.min(max, Math.max(min, v));
  };

  Canio.getToolbox = getToolbox = function(c, cb) {
    var ctx, img_data;
    return nb(cb, [c, ctx = c.getContext('2d'), img_data = ctx.getImageData(0, 0, c.width, c.height), img_data.data]);
  };

  Canio.make = make = function() {
    var c, cb, element, height, origin, p, width, _ref;
    p = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _ref = fff(p, 800, 600), cb = _ref[0], width = _ref[1], height = _ref[2], origin = _ref[3];
    if (width.width && width.height) {
      element = width;
      width = element.width;
      height = element.height;
      origin = (element != null ? typeof element.getAttribute === "function" ? element.getAttribute('id') : void 0 : void 0) || (element != null ? typeof element.getAttribute === "function" ? element.getAttribute('origin') : void 0 : void 0);
    }
    c = document.createElement('canvas');
    c.width = width;
    c.height = height;
    if (origin) {
      c.setAttribute('origin', origin);
    }
    return nb(cb, c);
  };

  Canio.newToolbox = newToolbox = function() {
    var cb, height, origin, p, width, _ref;
    p = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _ref = fff(p), cb = _ref[0], width = _ref[1], height = _ref[2], origin = _ref[3];
    return Canio.getToolbox(make(width, height, origin), cb);
  };

  Canio.copy = copy = function(c, cb) {
    var new_c, new_ctx, _ref;
    _ref = newToolbox(c), new_c = _ref[0], new_ctx = _ref[1];
    new_ctx.drawImage(c, 0, 0, c.width, c.height);
    return nb(cb, new_c);
  };

  Canio.byImage = byImage = function(img, cb) {
    if (img.width && img.height) {
      return copy(img, cb);
    } else {
      cbr(cb, 'Canio.byImage (only if the image is not "loaded")');
      if (isFunction(cb)) {
        img.onload = function() {
          return Canio.byImage(img, cb);
        };
      }
      return true;
    }
  };

  Canio.byArray = byArray = function(a, w, h, cb) {
    var c, ctx, i, imgd, pxs, _ref;
    _ref = newToolbox(w, h), c = _ref[0], ctx = _ref[1], imgd = _ref[2], pxs = _ref[3];
    i = 0;
    while (i < pxs.length) {
      pxs[i] = a[i];
      i = i + 1;
    }
    ctx.putImageData(imgd, 0, 0);
    return nb(cb, c);
  };

  Canio.toImage = toImage = function() {
    var c, cb, img, mime, p, _ref;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 'image/png'), cb = _ref[0], mime = _ref[1];
    img = new Image();
    img.src = c.toDataURL(mime, "");
    return nb(cb, img);
  };

  Canio.toArray = toArray = function(c, cb) {
    var a, ctx, i, imgd, px, _ref;
    a = [];
    _ref = getToolbox(c), c = _ref[0], ctx = _ref[1], imgd = _ref[2], px = _ref[3];
    if (Uint8Array) {
      a = new Uint8Array(new ArrayBuffer(px.length));
    }
    i = 0;
    while (i < px.length) {
      a[i] = px[i];
      i = i + 1;
    }
    return a;
  };

  Canio.hardResize = hardResize = function(c, w, h, cb) {
    var new_c, new_ctx, _ref;
    _ref = Canio.newToolbox(w, h), new_c = _ref[0], new_ctx = _ref[1];
    new_ctx.drawImage(c, 0, 0, w, h);
    return nb(cb, new_c);
  };

  Canio.resize = resize = function() {
    var c, cb, first, max, min, new_c, new_ctx, p, r, second, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    max = {
      width: null,
      height: null
    };
    min = {
      width: null,
      height: null
    };
    _ref = fff(p, 800, null, null, null, null, null), cb = _ref[0], max['width'] = _ref[1], max['height'] = _ref[2], min['width'] = _ref[3], min['height'] = _ref[4], first = _ref[5];
    second = null;
    r = {
      width: null,
      height: null
    };
    if (first === 'width') {
      second = 'height';
    } else if (first === 'height') {
      second = 'width';
    } else {
      if (c.height > c.width) {
        first = 'height';
        second = 'width';
        dlog('hochformat');
      } else {
        dlog('height' + c.height);
        dlog('width' + c.width);
        first = 'width';
        second = 'height';
        dlog('querformat');
      }
    }
    console.log('hallo');
    dlog('first: ' + first);
    dlog('second: ' + second);
    dlog(c[first]);
    if (max[first] && (c[first] > max[first] || c[second] > max[second])) {
      dlog('a');
      r[second] = c[second] * max[first] / c[first];
      r[first] = max[first];
      if (r[second] > max[second]) {
        dlog('b');
        r[first] = c[first] * max[second] / c[second];
        r[second] = max[second];
      }
    } else if (min[first] && (c[first] < min[first] || c[second] > min[second])) {
      dlog('c');
      r[first] = c[first] * min[second] / c[second];
      r[second] = min[second];
      if (r[first] < min[first]) {
        dlog('d');
        r[second] = c[second] * min[first] / c[first];
        r[first] = min[first];
      }
    } else {
      dlog('e');
      r[first] = c[first];
      r[second] = c[second];
      dlog('f');
    }
    _ref1 = newToolbox(r.width, r.height, (c != null ? c.getAttribute('id') : void 0) || (c != null ? c.getAttribute('origin') : void 0)), new_c = _ref1[0], new_ctx = _ref1[1];
    new_ctx.drawImage(c, 0, 0, r.width, r.height);
    dlog('g');
    dlog(new_c);
    dlog(cb);
    return nb(cb, new_c);
  };

  Canio.scale = scale = function() {
    var c, cb, new_c, new_ctx, new_height, new_width, p, x, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 1), cb = _ref[0], x = _ref[1];
    dlog('scale it by ' + x);
    new_width = c.width * x;
    new_height = c.height * x;
    _ref1 = newToolbox(new_width, new_height, (c != null ? c.getAttribute('id') : void 0) || (c != null ? c.getAttribute('origin') : void 0)), new_c = _ref1[0], new_ctx = _ref1[1];
    new_ctx.drawImage(c, 0, 0, new_width, new_height);
    return nb(cb, new_c);
  };

  Canio.crop = crop = function() {
    var c, cb, crop_height, crop_width, crop_x, crop_y, new_c, new_ctx, p, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 0, 0, c.width / 2, c.height / 2), cb = _ref[0], crop_x = _ref[1], crop_y = _ref[2], crop_width = _ref[3], crop_height = _ref[4];
    _ref1 = newToolbox(crop_width, crop_height, (c != null ? c.getAttribute('id') : void 0) || (c != null ? c.getAttribute('origin') : void 0)), new_c = _ref1[0], new_ctx = _ref1[1];
    new_ctx.drawImage(c, crop_x, crop_y, crop_width, crop_height, 0, 0, crop_width, crop_height);
    return nb(cb, new_c);
  };

  Canio.rgba = rgba = function() {
    var a, b, c, cb, ctx, extended, filter, g, h, i, imgd, new_c, p, pxs, r, u8, w, x, y, _ref, _ref1, _ref2, _ref3, _ref4;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    dlog('inrgba');
    _ref = fff(p, null, false), cb = _ref[0], filter = _ref[1], extended = _ref[2];
    dlog(typeof filter);
    if (!isFunction(filter)) {
      dlog('filter not a function');
      return false;
    }
    _ref1 = getToolbox(c), c = _ref1[0], ctx = _ref1[1], imgd = _ref1[2], pxs = _ref1[3];
    _ref2 = [c.width, c.height], w = _ref2[0], h = _ref2[1];
    dlog('rgba canvas size');
    dlog([w, h]);
    u8 = new Uint8Array(new ArrayBuffer(pxs.length));
    y = 0;
    dlog('rgbabeforewhile');
    while (y < h) {
      x = 0;
      while (x < w) {
        i = (y * w + x) * 4;
        r = i;
        g = i + 1;
        b = i + 2;
        a = i + 3;
        if (!extended) {
          _ref3 = filter(pxs[r], pxs[g], pxs[b], pxs[a], i), u8[r] = _ref3[0], u8[g] = _ref3[1], u8[b] = _ref3[2], u8[a] = _ref3[3];
        } else {
          _ref4 = filter(pxs[r], pxs[g], pxs[b], pxs[a], i, c), u8[r] = _ref4[0], u8[g] = _ref4[1], u8[b] = _ref4[2], u8[a] = _ref4[3];
        }
        x = x + 1;
      }
      y = y + 1;
    }
    new_c = Canio.byArray(u8, w, h);
    dlog('rgba return value');
    dlog(new_c);
    return nb(cb, new_c);
  };

  Canio.rotateRight = function(c, cb) {
    var new_c, new_ctx, _ref;
    _ref = newToolbox(c), new_c = _ref[0], new_ctx = _ref[1];
    new_ctx.rotate(90 * Math.PI / 180);
    new_ctx.drawImage(c, 0, c.height * -1);
    return nb(cb, c);
  };

  Canio.rotateLeft = function(c, cb) {
    var new_c, new_ctx, _ref;
    _ref = newToolbox(c), new_c = _ref[0], new_ctx = _ref[1];
    new_ctx.rotate(-90 * Math.PI / 180);
    new_ctx.drawImage(c, c.width * -1, 0);
    return nb(cb, c);
  };

  Canio.flip = function(c, cb) {
    var new_c, new_ctx, _ref;
    _ref = newToolbox(c), new_c = _ref[0], new_ctx = _ref[1];
    new_ctx.rotate(Math.PI);
    new_ctx.drawImage(c, c.width * -1, c.height * -1);
    return nb(cb, c);
  };

  Canio.mirror = function(c, cb) {
    var new_c, new_ctx, _ref;
    _ref = newToolbox(c), new_c = _ref[0], new_ctx = _ref[1];
    new_ctx.translate(c2.width / 2, 0);
    new_ctx.scale(-1, 1);
    new_ctx.drawImage(c, (c2.width / 2) * -1, 0);
    return nb(cb, c);
  };

  Canio.noise = function() {
    var amount, c, cb, dblHlp, i, k, new_c, new_ctx, new_imgd, new_pxs, noise, p, px, _i, _len, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 20), cb = _ref[0], amount = _ref[1];
    _ref1 = getToolbox(copy(c)), new_c = _ref1[0], new_ctx = _ref1[1], new_imgd = _ref1[2], new_pxs = _ref1[3];
    for (i = _i = 0, _len = new_pxs.length; _i < _len; i = ++_i) {
      px = new_pxs[i];
      noise = Math.round(amount - Math.random() * amount / 2);
      dblHlp = 0;
      k = 0;
      while (k < 3) {
        new_pxs[i + k] = clamp(noise + new_pxs[i + k]);
        k = k + 1;
      }
    }
    new_ctx.putImageData(new_imgd, 0, 0);
    return nb(cb, new_c);
  };

  Canio.vignette = function() {
    var black, c, cb, gradient, new_c, new_ctx, new_imgd, new_pxs, outerRadius, p, white, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 0.2, 0.8), cb = _ref[0], white = _ref[1], black = _ref[2];
    _ref1 = getToolbox(copy(c)), new_c = _ref1[0], new_ctx = _ref1[1], new_imgd = _ref1[2], new_pxs = _ref1[3];
    outerRadius = Math.sqrt(Math.pow(new_c.width / 2, 2) + Math.pow(new_c.height / 2, 2));
    new_ctx.globalCompositeOperation = 'source-over';
    gradient = new_ctx.createRadialGradient(new_c.width / 2, new_c.height / 2, 0, new_c.width / 2, new_c.height / 2, outerRadius);
    gradient.addColorStop(0, 'rgba(0,0,0,0)');
    gradient.addColorStop(0.65, 'rgba(0,0,0,0)');
    gradient.addColorStop(1, 'rgba(0,0,0,' + black + ')');
    new_ctx.fillStyle = gradient;
    new_ctx.fillRect(0, 0, new_c.width, new_c.height);
    new_ctx.globalCompositeOperation = 'lighter';
    gradient = new_ctx.createRadialGradient(new_c.width / 2, new_c.height / 2, 0, new_c.width / 2, new_c.height / 2, outerRadius);
    gradient.addColorStop(0, 'rgba(255,255,255,' + white + ')');
    gradient.addColorStop(0.65, 'rgba(255,255,255,0)');
    gradient.addColorStop(1, 'rgba(0,0,0,0)');
    new_ctx.fillStyle = gradient;
    new_ctx.fillRect(0, 0, new_c.width, new_c.height);
    return nb(cb, new_c);
  };

  Canio.saturate = function() {
    var c, cb, filter, p, t, _ref;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 0.3), cb = _ref[0], t = _ref[1];
    filter = function(r, g, b, a) {
      var average;
      average = (r + g + b) / 3;
      return [clamp(average + t * (r - average)), clamp(average + t * (g - average)), clamp(average + t * (b - average)), a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.desaturate = function() {
    var c, cb, p, t, _ref;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 0.7), cb = _ref[0], t = _ref[1];
    return Canio.saturate(c, 1 - t, cb);
  };

  Canio.merge = function() {
    var c, cb, filter, p, p_c, p_ctx, p_imgd, p_pxs, picture, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    dlog('inmerge');
    _ref = fff(p, null), cb = _ref[0], picture = _ref[1];
    while (!picture) {
      return false;
    }
    _ref1 = Canio.getToolbox(Canio.hardResize(picture, c.width, c.height)), p_c = _ref1[0], p_ctx = _ref1[1], p_imgd = _ref1[2], p_pxs = _ref1[3];
    filter = function(r, g, b, a, i) {
      var blue, green, red;
      red = clamp((r * p_pxs[i]) / 255);
      green = clamp((g * p_pxs[i + 1]) / 255);
      blue = clamp((b * p_pxs[i + 2]) / 255);
      return [red, green, blue, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.hardmerge = function() {
    var c, p;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  };

  Canio.negmerge = function() {
    var c, cb, filter, p, p_c, p_ctx, p_imgd, p_pxs, picture, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    dlog('inmerge');
    _ref = fff(p, null), cb = _ref[0], picture = _ref[1];
    while (!picture) {
      return false;
    }
    _ref1 = Canio.getToolbox(Canio.hardResize(picture, c.width, c.height)), p_c = _ref1[0], p_ctx = _ref1[1], p_imgd = _ref1[2], p_pxs = _ref1[3];
    filter = function(r, g, b, a, i) {
      var blue, green, red;
      red = clamp((r / p_pxs[i]) * 255);
      green = clamp((g / p_pxs[i + 1]) * 255);
      blue = clamp((b / p_pxs[i + 2]) * 255);
      return [red, green, blue, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.lightmerge = function() {
    var c, cb, filter, p, p_c, p_ctx, p_imgd, p_pxs, picture, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, null), cb = _ref[0], picture = _ref[1];
    while (!picture) {
      return false;
    }
    _ref1 = Canio.getToolbox(Canio.hardResize(picture, c.width, c.height)), p_c = _ref1[0], p_ctx = _ref1[1], p_imgd = _ref1[2], p_pxs = _ref1[3];
    filter = function(r, g, b, a, i) {
      r = (r > p_pxs[i] ? r : p_pxs[i]);
      g = (g > p_pxs[i + 1] ? g : p_pxs[i + 1]);
      b = (b > p_pxs[i + 2] ? b : p_pxs[i + 2]);
      return [r, g, b, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.darkmerge = function() {
    var c, cb, filter, p, p_c, p_ctx, p_imgd, p_pxs, picture, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, null), cb = _ref[0], picture = _ref[1];
    while (!picture) {
      return false;
    }
    _ref1 = Canio.getToolbox(Canio.hardResize(picture, c.width, c.height)), p_c = _ref1[0], p_ctx = _ref1[1], p_imgd = _ref1[2], p_pxs = _ref1[3];
    filter = function(r, g, b, a, i) {
      r = (r < p_pxs[i] ? r : p_pxs[i]);
      g = (g < p_pxs[i + 1] ? g : p_pxs[i + 1]);
      b = (b < p_pxs[i + 2] ? b : p_pxs[i + 2]);
      return [r, g, b, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  getGrayscaleValue = function(r, g, b) {
    return r * 0.3 + g * 0.59 + b * 0.11;
  };

  Canio.lightermerge = function() {
    var c, cb, filter, p, p_c, p_ctx, p_imgd, p_pxs, picture, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, null), cb = _ref[0], picture = _ref[1];
    while (!picture) {
      return false;
    }
    _ref1 = Canio.getToolbox(Canio.hardResize(picture, c.width, c.height)), p_c = _ref1[0], p_ctx = _ref1[1], p_imgd = _ref1[2], p_pxs = _ref1[3];
    filter = function(r, g, b, a, i) {
      var lighter;
      lighter = (getGrayscaleValue(r, g, b) > getGrayscaleValue(p_pxs[i], p_pxs[i + 1], p_pxs[i + 2]) ? true : false);
      r = (lighter ? r : p_pxs[i]);
      g = (lighter ? g : p_pxs[i + 1]);
      b = (lighter ? b : p_pxs[i + 2]);
      return [r, g, b, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.darkermerge = function() {
    var c, cb, filter, p, p_c, p_ctx, p_imgd, p_pxs, picture, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, null), cb = _ref[0], picture = _ref[1];
    while (!picture) {
      return false;
    }
    _ref1 = Canio.getToolbox(Canio.hardResize(picture, c.width, c.height)), p_c = _ref1[0], p_ctx = _ref1[1], p_imgd = _ref1[2], p_pxs = _ref1[3];
    filter = function(r, g, b, a, i) {
      var darker;
      darker = (getGrayscaleValue(r, g, b) < getGrayscaleValue(p_pxs[i], p_pxs[i + 1], p_pxs[i + 2]) ? true : false);
      r = (darker ? r : p_pxs[i]);
      g = (darker ? g : p_pxs[i + 1]);
      b = (darker ? b : p_pxs[i + 2]);
      return [r, g, b, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.blend = function() {
    var amount, c, cb, filter, neg_amount, p, p_c, p_ctx, p_imgd, p_pxs, picture, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, null, 0.5), cb = _ref[0], picture = _ref[1], amount = _ref[2];
    while (!picture) {
      return false;
    }
    _ref1 = Canio.getToolbox(Canio.hardResize(picture, c.width, c.height)), p_c = _ref1[0], p_ctx = _ref1[1], p_imgd = _ref1[2], p_pxs = _ref1[3];
    neg_amount = 1 - amount;
    filter = function(r, g, b, a, i) {
      var blue, green, red;
      red = clamp((r * neg_amount) + (p_pxs[i] * amount));
      green = clamp((g * neg_amount) + (p_pxs[i + 1] * amount));
      blue = clamp((b * neg_amount) + (p_pxs[i + 2] * amount));
      return [red, green, blue, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.viewfinder = function(c, cb) {
    var pic;
    cbr(cb, 'Canio.viewfinder');
    pic = new Image();
    pic.onload = function() {
      return Canio.merge(c, pic, cb);
    };
    pic.src = Caniodataurls.viewfinder;
    return true;
  };

  Canio.oldschool = function(c, cb) {
    var pic;
    cbr(cb, 'Canio.oldschool');
    pic = new Image();
    pic.onload = function() {
      return Canio.lightermerge(c, pic, 1, cb);
    };
    pic.src = Caniodataurls.oldschool;
    return true;
  };

  Canio.many = function() {
    var action, actions, c, cb, p, paramA, params, _ref, _ref1, _ref2;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p), cb = _ref[0], actions = _ref[1], params = _ref[2];
    cbr(cb);
    action = (_ref1 = actions != null ? actions.shift() : void 0) != null ? _ref1 : null;
    paramA = (_ref2 = params != null ? params.shift() : void 0) != null ? _ref2 : [];
    while (!Array.isArray(paramA)) {
      paramA = [paramA];
    }
    if (actions.length > 0) {
      return action.apply(null, [c, (function(c) {
        return Canio.many(c, cb, actions, params);
      })].concat(__slice.call(paramA)));
    } else {
      return action(c, cb, paramA);
    }
  };

  Canio.nothing = function() {
    var c, cb, filter, p;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    cb = fff(p)[0];
    filter = function(r, g, b, a) {
      return [r, g, b, a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.curve = function() {
    var bc, c, cb, filter, gc, p, rc;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    cb = fff(p)[0];
    rc = [0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 12, 12, 12, 12, 13, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 17, 18, 19, 19, 20, 21, 22, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 42, 44, 45, 47, 48, 49, 52, 54, 55, 57, 59, 60, 62, 65, 67, 69, 70, 72, 74, 77, 79, 81, 83, 86, 88, 90, 92, 94, 97, 99, 101, 103, 107, 109, 111, 112, 116, 118, 120, 124, 126, 127, 129, 133, 135, 136, 140, 142, 143, 145, 149, 150, 152, 155, 157, 159, 162, 163, 165, 167, 170, 171, 173, 176, 177, 178, 180, 183, 184, 185, 188, 189, 190, 192, 194, 195, 196, 198, 200, 201, 202, 203, 204, 206, 207, 208, 209, 211, 212, 213, 214, 215, 216, 218, 219, 219, 220, 221, 222, 223, 224, 225, 226, 227, 227, 228, 229, 229, 230, 231, 232, 232, 233, 234, 234, 235, 236, 236, 237, 238, 238, 239, 239, 240, 241, 241, 242, 242, 243, 244, 244, 245, 245, 245, 246, 247, 247, 248, 248, 249, 249, 249, 250, 251, 251, 252, 252, 252, 253, 254, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255];
    gc = [0, 0, 1, 2, 2, 3, 5, 5, 6, 7, 8, 8, 10, 11, 11, 12, 13, 15, 15, 16, 17, 18, 18, 19, 21, 22, 22, 23, 24, 26, 26, 27, 28, 29, 31, 31, 32, 33, 34, 35, 35, 37, 38, 39, 40, 41, 43, 44, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 56, 57, 58, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 79, 80, 81, 83, 84, 85, 86, 88, 89, 90, 92, 93, 94, 95, 96, 97, 100, 101, 102, 103, 105, 106, 107, 108, 109, 111, 113, 114, 115, 117, 118, 119, 120, 122, 123, 124, 126, 127, 128, 129, 131, 132, 133, 135, 136, 137, 138, 140, 141, 142, 144, 145, 146, 148, 149, 150, 151, 153, 154, 155, 157, 158, 159, 160, 162, 163, 164, 166, 167, 168, 169, 171, 172, 173, 174, 175, 176, 177, 178, 179, 181, 182, 183, 184, 186, 186, 187, 188, 189, 190, 192, 193, 194, 195, 195, 196, 197, 199, 200, 201, 202, 202, 203, 204, 205, 206, 207, 208, 208, 209, 210, 211, 212, 213, 214, 214, 215, 216, 217, 218, 219, 219, 220, 221, 222, 223, 223, 224, 225, 226, 226, 227, 228, 228, 229, 230, 231, 232, 232, 232, 233, 234, 235, 235, 236, 236, 237, 238, 238, 239, 239, 240, 240, 241, 242, 242, 242, 243, 244, 245, 245, 246, 246, 247, 247, 248, 249, 249, 249, 250, 251, 251, 252, 252, 252, 253, 254, 255];
    bc = [53, 53, 53, 54, 54, 54, 55, 55, 55, 56, 57, 57, 57, 58, 58, 58, 59, 59, 59, 60, 61, 61, 61, 62, 62, 63, 63, 63, 64, 65, 65, 65, 66, 66, 67, 67, 67, 68, 69, 69, 69, 70, 70, 71, 71, 72, 73, 73, 73, 74, 74, 75, 75, 76, 77, 77, 78, 78, 79, 79, 80, 81, 81, 82, 82, 83, 83, 84, 85, 85, 86, 86, 87, 87, 88, 89, 89, 90, 90, 91, 91, 93, 93, 94, 94, 95, 95, 96, 97, 98, 98, 99, 99, 100, 101, 102, 102, 103, 104, 105, 105, 106, 106, 107, 108, 109, 109, 110, 111, 111, 112, 113, 114, 114, 115, 116, 117, 117, 118, 119, 119, 121, 121, 122, 122, 123, 124, 125, 126, 126, 127, 128, 129, 129, 130, 131, 132, 132, 133, 134, 134, 135, 136, 137, 137, 138, 139, 140, 140, 141, 142, 142, 143, 144, 145, 145, 146, 146, 148, 148, 149, 149, 150, 151, 152, 152, 153, 153, 154, 155, 156, 156, 157, 157, 158, 159, 160, 160, 161, 161, 162, 162, 163, 164, 164, 165, 165, 166, 166, 167, 168, 168, 169, 169, 170, 170, 171, 172, 172, 173, 173, 174, 174, 175, 176, 176, 177, 177, 177, 178, 178, 179, 180, 180, 181, 181, 181, 182, 182, 183, 184, 184, 184, 185, 185, 186, 186, 186, 187, 188, 188, 188, 189, 189, 189, 190, 190, 191, 191, 192, 192, 193, 193, 193, 194, 194, 194, 195, 196, 196, 196, 197, 197, 197, 198, 199];
    filter = function(r, g, b, a) {
      return [rc[r], rc[g], rc[b], a];
    };
    return Canio.rgba(c, cb, filter);
  };

  Canio.screen = function() {
    var bb, c, cb, filter, gg, p, rr, strength, _ref;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 227, 12, 169, 0.2), cb = _ref[0], rr = _ref[1], gg = _ref[2], bb = _ref[3], strength = _ref[4];
    filter = function(r, g, b, a) {
      return [255 - ((255 - r) * (255 - rr * strength) / 255), 255 - ((255 - g) * (255 - gg * strength) / 255), 255 - ((255 - b) * (255 - bb * strength) / 255), a];
    };
    return Canio.rgba(c, cb, filter);
  };

  ifw = function() {
    var c, cb, ctx, image_filters_func, imgd, new_c, new_ctx, new_imgd, new_px, p, px, _ref, _ref1;
    c = arguments[0], cb = arguments[1], image_filters_func = arguments[2], p = 4 <= arguments.length ? __slice.call(arguments, 3) : [];
    _ref = getToolbox(c), c = _ref[0], ctx = _ref[1], imgd = _ref[2], px = _ref[3];
    _ref1 = newToolbox(c), new_c = _ref1[0], new_ctx = _ref1[1], new_imgd = _ref1[2], new_px = _ref1[3];
    nb(function() {
      return new_ctx.putImageData(image_filters_func.apply(null, [imgd].concat(__slice.call(p))), 0, 0);
    });
    return nb(cb, new_c);
  };

  mF = function() {
    var defaults, image_filters_func;
    image_filters_func = arguments[0], defaults = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return function() {
      var c, cb, defaulted_p, p;
      c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      defaulted_p = fff(p, defaults);
      cb = defaulted_p.shift();
      return ifw.apply(null, [c, cb, image_filters_func].concat(__slice.call(defaulted_p)));
    };
  };

  Canio.binarize = mF(ImageFilters.Binarize, 0.5);

  Canio.boxBlur = mF(ImageFilters.BoxBlur, 3, 3, 2);

  Canio.gaussianBlur = mF(ImageFilters.GaussianBlur, 2);

  Canio.stackBlur = mF(ImageFilters.StackBlur, 6);

  Canio.brightness = mF(ImageFilters.brightness, 1);

  Canio.brightnessConstrastGimp = mF(ImageFilters.BrightnessContrastGimp, 50, 50);

  Canio.brightnessConstrastPhotoshop = mF(ImageFilters.BrightnessContrastPhotoshop, 50, 50);

  Canio.Channels = function(channel_string) {
    var channel;
    if (channel_string === "blue" || channel_string === "b") {
      channel = 3;
    } else if (channel_string === "green" || channel_string === "g") {
      channel = 2;
    } else {
      channel = channel_string;
    }
    return mF(ImageFilters.Channels, channel);
  };

  Canio.colorTransform = mF(ImageFilters.ColorTransformFilter, 1, 1, 1, 0, 0, 0);

  Canio.dither = mF(ImageFilters.Dither, 2);

  Canio.edge = mF(ImageFilters.Edge);

  Canio.emboss = mF(ImageFilters.Emboss);

  Canio.enrich = mF(ImageFilters.Enrich);

  Canio.gamma = mF(ImageFilters.Gamma, 2);

  Canio.grayscale = mF(ImageFilters.Grayscale);

  Canio.HSLAdjustment = mF(ImageFilters.HSLAdjustment, 0, 0, 0);

  Canio.invert = mF(ImageFilters.Invert);

  Canio.mosaic = mF(ImageFilters.Mosaic, 10);

  Canio.oil = mF(ImageFilters.Oil, 4, 30);

  Canio.opacity = mF(ImageFilters.OpacityFilter, 10);

  Canio.posterize = mF(ImageFilters.Posterize, 8);

  Canio.sepia = mF(ImageFilters.Sepia);

  Canio.sharpen = mF(ImageFilters.Sharpen, 3);

  Canio.solarize = mF(ImageFilters.Solarize);

  Canio.twirl = mF(ImageFilters.Twril, 0.5, 0.5, 100, 360);

  window.Canio = Canio;

}).call(this);
